## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop('EIN',1)
application_df = application_df.drop('NAME',1)
application_df.head()

<ipython-input-2-a9e0dc3679a3>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df = application_df.drop('EIN',1)
<ipython-input-2-a9e0dc3679a3>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df = application_df.drop('NAME',1)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_count = application_df['APPLICATION_TYPE'].value_counts()
application_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_count[application_count < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_count[application_count < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_count[classification_count < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"],1).values
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

<ipython-input-10-9b8978084081>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = application_df.drop(["IS_SUCCESSFUL"],1).values

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [37]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  10
hidden_nodes_layer2 = 10
hidden_nodes_layer3 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_20 (Dense)            (None, 10)                440

 dense_21 (Dense)            (None, 10)                110

 dense_22 (Dense)            (None, 10)                110

 dense_23 (Dense)            (None, 1)                 11

=================================================================
Total params: 671
Trainable params: 671
Non-trainable params: 0
_________________________________________________________________

In [38]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [39]:
import os
import math

checkpoint_path = "module_1/cp.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

batch_size = 32

# Calculate the number of batches per epoch
n_batches = len(X_train_scaled) / batch_size
n_batches = math.ceil(n_batches)    # round up the number of batches to the nearest whole integer

# Create a callback that saves the model's weights every 5 epochs
cp_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    save_freq=5*n_batches)

In [40]:
# Train the model
fit_model = nn.fit(X_train_scaled,
                   y_train,
                   epochs=30,
                   batch_size=batch_size,
                   callbacks=[cp_callback])

Epoch 1/30
804/804 [==============================] - 2s 1ms/step - loss: 0.5893 - accuracy: 0.7163
Epoch 2/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5621 - accuracy: 0.7283
Epoch 3/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5567 - accuracy: 0.7304
Epoch 4/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5541 - accuracy: 0.7309
Epoch 5/30
783/804 [============================>.] - ETA: 0s - loss: 0.5518 - accuracy: 0.7339
Epoch 5: saving model to module_1/cp.ckpt
804/804 [==============================] - 1s 2ms/step - loss: 0.5524 - accuracy: 0.7333
Epoch 6/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5518 - accuracy: 0.7325
Epoch 7/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5507 - accuracy: 0.7338
Epoch 8/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7339
Epoch 9/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5493 - accuracy: 0.7339
Epoch 10/30
771/804 [===========================>..] - ETA: 0s - loss: 0.5477 - accuracy: 0.7348
Epoch 10: saving model to module_1/cp.ckpt
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7341
Epoch 11/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7350
Epoch 12/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7349
Epoch 13/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7353
Epoch 14/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7358
Epoch 15/30
803/804 [============================>.] - ETA: 0s - loss: 0.5474 - accuracy: 0.7359
Epoch 15: saving model to module_1/cp.ckpt
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7360
Epoch 16/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7353
Epoch 17/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7362
Epoch 18/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5463 - accuracy: 0.7370
Epoch 19/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5459 - accuracy: 0.7362
Epoch 20/30
770/804 [===========================>..] - ETA: 0s - loss: 0.5458 - accuracy: 0.7360
Epoch 20: saving model to module_1/cp.ckpt
804/804 [==============================] - 1s 1ms/step - loss: 0.5459 - accuracy: 0.7358
Epoch 21/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7355
Epoch 22/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5456 - accuracy: 0.7360
Epoch 23/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7364
Epoch 24/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5450 - accuracy: 0.7364
Epoch 25/30
790/804 [============================>.] - ETA: 0s - loss: 0.5459 - accuracy: 0.7366
Epoch 25: saving model to module_1/cp.ckpt
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7365
Epoch 26/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7352
Epoch 27/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7349
Epoch 28/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7357
Epoch 29/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7353
Epoch 30/30
799/804 [============================>.] - ETA: 0s - loss: 0.5453 - accuracy: 0.7368
Epoch 30: saving model to module_1/cp.ckpt
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7371

In [41]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5531 - accuracy: 0.7266 - 367ms/epoch - 1ms/step
Loss: 0.553108274936676, Accuracy: 0.7266472578048706

In [45]:
# Export our model to HDF5 file
filename = '/h5_files/AlphabetSoupCharity.h5'


# Save the model to a HDF5 file
nn.save(filename)